plugins:
  custom_wizard_enabled: 
    default: true
    client: true
  wizard_redirect_exclude_paths:
    client: true
    type: list
    default: 'admin'
    choices:
      - admin
      - privacy
  wizard_recognised_image_upload_formats:
    client: true
    default: "jpg|jpeg|png|gif"
    refresh: true
    type: list
    list_type: compact
  wizard_apis_enabled:
    client: true
    default: false